version: "3"

services:
  web:
    image: nginx
    volumes:
      - ./lib:/etc/nginx/html
      - ./local/cert:/etc/nginx/ssl
      - ./local/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
      - 8003:8003
